### ISSUE TITLE
run cargo clippy

### ISSUE THREAD

**Issue by magnusuMET** [gauteh/dars#2]
A lot of unneccessary strings are created when handling the errors, using the pattern
```rust
e.unwrap(anyhow!("{}", "x failed")
```
This will always evaluate the `anyhow`, even when not used. This is a lint in clippy, which also picks up some other "errors"

**Comment by gauteh** [comment]
Thanks for the suggestion, should definitely learn how to do this properly.

**Comment by magnusuMET** [comment]
clippy is available as `rustup component add clippy`, could also use `rustup component add rustfmt` and run `cargo fmt`

**Comment by gauteh** [comment]
Thanks, I did have it in there, but removed it since clippy was not available in nightly. rustmft should probably also be run.

(btw: maybe you have some thoughts on #3, but I'm pretty sure the error is not in netcdf)

**Comment by magnusuMET** [comment]
You'll have to run `cargo fmt -- --check` to emit build failure

**Comment by gauteh** [comment]
Criticals fixed, deal with rest as we go.
