### ISSUE TITLE
Automatically build tags and publish docker images

### ISSUE THREAD

**Issue by magnusuMET** [gauteh/dars#21]
We should introduce a CI/CD workflow which build and deploys this image.

This can either be done under https://hub.docker.com/r/gauteh/dars or on a mirrored copy to gitlab.met.no which can deploy to the internal registry.

**Comment by gauteh** [comment]
Yes. I think travis is shut down as well, need to port CI. Maybe github actions is the easiest.

**Comment by magnusuMET** [comment]
I'll copy some github actions from somewhere to get CI up again
