### ISSUE TITLE
memory leak when making requests

### ISSUE THREAD

**Issue by gauteh** [gauteh/dars#3]
There might be a memory leak related to the number of requests made. After testing rust-netcdf, and not being able to provoke the issue there, I believe the leak could be this bug: https://github.com/hyperium/hyper/issues/1790#issuecomment-575880931

**Comment by magnusuMET** [comment]
There has been suspicions in https://github.com/Unidata/netcdf-c/issues/1575

**Comment by magnusuMET** [comment]
But this is limited to opening and closing files, I think you keep files open?

**Comment by gauteh** [comment]
Yes, I tried to debug by creating an infinite loop reading vars (from the same file handle), but that does not seem to cause a leak.

**Comment by gauteh** [comment]
No longer observed. Conclusion upstream also seems to be that this is not a real issue.
